config/routes.rb
Rails.application.routes.draw do
  resources :foods
  resources :cart_items
  resources :carts
  post "checkout" => "checkout#show", as: :checkout
  post "payment" => "checkout#create", as: :payment
  
  get 'welcome/index'

  devise_for :users

  root 'welcome#index'

end

app/models/cart.rb
class Cart
  attr_reader :cart_data

  def initialize(cart_data)
    @cart_data = cart_data || {}
  end

  def increment(item_id)
    @cart_data[item_id] ||= 0
    @cart_data[item_id] += 1
  end

  def destroy
    @cart_data = nil
  end

  def delete
    @cart_data[item_id] = 0
  end

end

app/models/current_order.rb
class Current_Order
  attr_accessor :ordered_items
  attr_accessor :total
  attr_accessor :delivery_cost
  attr_accessor :final_amount

  def initialize(current_order)
    @ordered_items = current_order["items"] || {}
    current_order["details"] ||= {}
    @total = current_order["details"]["total"].to_i || 0
    @delivery_cost = 500
    @final_amount = current_order["details"]["final_amount"].to_i || 0
    @user = {}
    @transaction_id = ""
    @status = "pending"
  end

  def vat
    0.1 * @total
  end

  def update_order(order, args)
    @ordered_items = order["items"] || {}
    @total = order["details"]["total"] || 0
    @transaction_id = args[:transaction_id] || ""
    @status = args[:status] || "pending"
  end

  def save_order(current_user)
    user = current_user
    new_order = user.orders.new(total: @final_amount, vat: vat,
                                delivery_cost: @delivery_cost,
                                transaction_id: @transaction_id, status: @status)
    save_successful = new_order.save
    if save_successful
      @ordered_items.each do |index, details|
        new_order.order_items <<
          OrderItem.create(food_id: details["food"]["id"],
                           quantity: details["qty"])
      end
    end
    save_successful
  end

end

app/models/food.rb
class Food < FoodBase

	has_many :order_items
  has_many :orders, through: :order_items

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "default_image.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/food_base.rb
class FoodBase < ActiveRecord::Base
  establish_connection DB_FOODS
  self.abstract_class = true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :food
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_action :load_cart
  before_action :load_current_order

  def load_cart
    @cart ||= Cart.new(session[:cart])
  end

  def load_current_order
    session[:order] ||= {}
    @current_order ||= Current_Order.new(session[:order])
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def create
    @cart.increment(params[:food_id])
    session[:cart] = @cart.cart_data
    redirect_to foods_path
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @cart_items = session[:cart]
    @ordered_foods = {}
    @total = 0
    unless session[:cart].nil?
      @cart_items.each do |food_id, qty|
        food = Food.find_by_id(food_id)
        @ordered_foods[food_id] = { food: food, qty: qty }
        @total += (food.price * qty)
      end
    end
    # debugger
    @current_order.ordered_items = @ordered_foods
    session[:order]["details"]["total"] = @total
    session[:order]["items"] = @ordered_foods
  end

  def destroy
    food_id = params[:id]
    @cart.cart_data.delete(food_id)
    redirect_to carts_path
  end

end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

  def show
    if current_user
      @current_order.ordered_items = session[:order]["items"]
    else
      redirect_to new_user_session_path
    end
  end

  # payment gateway integration not done
  # just confirm order for user
  def create
    if order_params[:status] == "completed"
      @current_order.update_order(session[:order], order_params)
      if @current_order.save_order(current_user)
        session[:order] = {}
        session[:cart] = {}
        flash[:success] = "Your order has been successfully placed."
        redirect_to root_path
      else
        flash[:error] = "An error occured while saving your order. Please try again."
        redirect_to cart_checkout_path
      end
    end
  end
  private

  def order_params
    { :status => params[:payment_status], :transaction_id => params[:txn_id]}
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :description, :price)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def cart_properties
    cart_properties = {}
    if session[:cart].nil? || session[:cart].empty?
      cart_properties["items_count"] = 0;
    else
      cart_properties["items_count"] = items_in_cart;
    end
    cart_properties
  end

  def items_in_cart
    items = 0
    if !session[:cart].nil? && session[:cart].length > 0
      session[:cart].each do |key, value|
        items += value
      end
    end
    items
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/index.html.haml
%p Carts items
- if @ordered_foods.length == 0
  %p Your cart is empth
- else
  %table.table.table-bordered
    %thead
      %tr
        %th Sr
        %th Name
        %th Description
        %th Quantity
        %th Price
        %th Item Total
    %tbody
      - @ordered_foods.each do |index, details|
        - food = details[:food]
        %tr
          %td= index
          %td= food.name
          %td= food.description
          %td= details[:qty]
          %td= food.price.to_i
          %td= food.price.to_i * details[:qty].to_i
    %tfoot
      %tr
        %td{colspan: 4}
        %td Total
        %td.total= @total

  = button_to 'Checkout', checkout_path, :class => "btn btn-success"

app/views/checkout/_current_order.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th Sr
      %th Name
      %th Description
      %th Quantity
      %th Price
      %th Item Total
  %tbody
    - @current_order.ordered_items.each do |index, details|
      - food = details[:food]
      %tr
        %td= index
        %td= details["food"]['name']
        %td= details["food"]['description']
        %td= details[:qty]
        %td= details["food"]['price']
        %td= details["food"]["price"] * details["qty"]
  %tfoot
    %tr
      %td{colspan: 4}
      %td Total
      %td.total= @current_order.total
    %tr
      %td{colspan: 4}
      %td VAT
      %td= @current_order.vat
    %tr
      %td{colspan: 4}
      %td Delivery cost
      %td= @current_order.delivery_cost
    - @current_order.final_amount = @current_order.total + @current_order.delivery_cost + @current_order.vat
    %tr
      %td{colspan: 4}
      %td Final amount
      %td= @current_order.final_amount

- session[:order][:details] = {"total"=>@current_order.total, "final_amount"=>@current_order.final_amount}

app/views/checkout/show.html.haml
%p Confirm your order
- if @current_order.ordered_items.length == 0
  %p Your cart is still empty.
- else
  = render "checkout/current_order"
%br

= link_to 'Back to my cart', carts_path, :class => "btn btn-success"
= button_to 'Confirm', payment_path(:payment_status => "completed", :transaction_id => SecureRandom.hex), :class => "btn btn-success pull-right"

app/views/foods/_form.html.haml
= form_for @food, html: { class: "form form-horizontal food" } do |f|
  .form-group
    = f.label :name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, class: 'form-control', required: true
    = f.error_span(:name)
  .form-group
    = f.label :description, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :description, class: 'form-control', required: true
    = f.error_span(:description)
  .form-group
    = f.label :price, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :price, class: 'form-control', required: true
    = f.error_span(:price)
  .form-group
    = f.label :image_file_name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :image_file_name, class: 'form-control', required: true
    = f.error_span(:image_file_name)
  .form-group
    = f.label :image_content_type, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :image_content_type, class: 'form-control', required: true
    = f.error_span(:image_content_type)
  .form-group
    = f.label :image_file_size, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :image_file_size, class: 'form-control', required: true
    = f.error_span(:image_file_size)
  .form-group
    = f.label :image_updated_at, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :image_updated_at, class: 'form-control', required: true
    = f.error_span(:image_updated_at)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), foods_path, :class => 'btn btn-default'

app/views/foods/edit.html.haml
- model_class = Food
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/foods/index.html.haml
- model_class = Food
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

.row
  - @foods.each do |food|
    .col-md-4
      .food_image
        = link_to(food) do
          = image_tag((food.image.url || "default_image.jpg"), :width => "100%", :height => "auto", :style => "max-width:100%", :class => "image-thumb", :alt => "food")
          %span.card-title= food.name
      .food_action
        = button_to "Add to cart", cart_items_path(food_id: food.id)

=# link_to t('.new', :default => t("helpers.links.new")), new_food_path, :class => 'btn btn-primary'

app/views/foods/new.html.haml
- model_class = Food
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/foods/show.html.haml
- model_class = Food
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @food.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @food.description
%p
  %strong= model_class.human_attribute_name(:price) + ':'
  %br
  = @food.price
%p
  = image_tag @food.image, :class => "img-responsive"

= link_to t('.back', :default => t("helpers.links.back")), foods_path, :class => 'btn btn-default'

= link_to t('.edit', :default => t("helpers.links.edit")), edit_food_path(@food), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), food_path(@food), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Khayali Pulao"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href=root_path) Khayali Pulao
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Foods", foods_path
          %ul.nav.navbar-nav.navbar-right
            %li.cart-holder
              = link_to carts_path do
                %i.fa.fa-shopping-cart
                = cart_properties['items_count']
            - if current_user
              %li= link_to "welcome, #{current_user.email}", "#"
              %li= link_to "Log out", destroy_user_session_path, :method => :delete
            - else
              %li= link_to "Log In", new_user_session_path
              %li= link_to "Sign Up", new_user_registration_path

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield
      %footer
        %p &copy; Company 2017

app/views/welcome/index.html.haml
%h1 Welcome
= image_tag "welcome.jpg", :class => "img-responsive"